import { parseSseDeltas, requestJson } from "@/lib/http";
import type {
  ChatMessage,
  ChatRequest,
  Execution,
} from "@/lib/types";

/** What the transport needs on top of the public ChatRequest: the wire model id. */
type WireRequest = ChatRequest & { model: string };

interface OpenAiChunk {
  choices?: {
    delta?: { content?: string | null };
  }[];
}

interface OpenAiToolResponse {
  choices?: Array<{
    message?: {
      content?: string | null;
      tool_calls?: Array<{
        function?: {
          name?: string;
          arguments?: string | Record<string, unknown>;
        };
      }>;
    };
  }>;
}

function pickDelta(payload: unknown): string | undefined {
  const chunk = payload as OpenAiChunk;
  return chunk.choices?.[0]?.delta?.content ?? undefined;
}

function toWireMessage(message: ChatMessage) {
  // Only user attachments are sent: assistant images were generated by the
  // model for the user, and replaying them as input breaks these providers.
  if (message.role !== "user" || !message.images?.length) {
    return { role: message.role, content: message.content };
  }

  return {
    role: message.role,
    content: [
      { type: "text", text: message.content },
      ...message.images.map((url) => ({
        type: "image_url",
        image_url: { url },
      })),
    ],
  };
}

function nativeTools(request: ChatRequest) {
  return (request.tools ?? []).map((tool) => ({
    type: "function" as const,
    function: {
      name: tool.name,
      description: tool.description,
      parameters: {
        type: "object",
        properties: {
          argument: {
            type: "string",
            description: "The single string argument for this tool.",
          },
        },
        required: ["argument"],
        additionalProperties: false,
      },
    },
  }));
}

function toolCallAsText(payload: OpenAiToolResponse): string | undefined {
  const toolCall = payload.choices?.[0]?.message?.tool_calls?.[0];
  const functionCall = toolCall?.function;
  if (!functionCall || typeof functionCall.name !== "string") return undefined;

  const name = functionCall.name.trim();
  if (!name) return undefined;

  const rawArguments = functionCall.arguments;
  let argument = "";

  if (typeof rawArguments === "string") {
    try {
      const parsed = JSON.parse(rawArguments) as { argument?: unknown };
      argument = typeof parsed.argument === "string" ? parsed.argument : rawArguments;
    } catch {
      argument = rawArguments;
    }
  } else if (rawArguments && typeof rawArguments === "object") {
    const value = rawArguments.argument;
    argument = typeof value === "string" ? value : JSON.stringify(rawArguments);
  }

  return JSON.stringify({
    name: name.toLowerCase(),
    arguments: { argument },
  });
}

/**
 * Transport for any OpenAI-compatible chat-completions endpoint. Nexus is the
 * only caller. Native tools are used only when the deployment opts in; normal
 * chat is streamed for the responsive UI.
 */
export function createOpenAiCompatibleProvider(config: {
  id: "nexus";
  label: string;
  execution: Execution;
  baseUrl: () => string | undefined;
  apiKey: () => string | undefined;
  requiresKey: boolean;
  supportsNativeTools?: boolean | (() => boolean);
  extraHeaders?: Record<string, string>;
}) {
  return {
    id: config.id,
    label: config.label,
    execution: config.execution,

    isConfigured() {
      if (!config.baseUrl()) return false;
      return config.requiresKey ? Boolean(config.apiKey()?.trim()) : true;
    },

    async *stream(request: WireRequest) {
      const key = config.apiKey();
      const baseUrl = config.baseUrl();

      if (!baseUrl) {
        throw new Error(`${config.label} base URL is not configured`);
      }

      const nativeAllowed =
        typeof config.supportsNativeTools === "function"
          ? config.supportsNativeTools()
          : Boolean(config.supportsNativeTools);

      const useNativeTools =
        nativeAllowed &&
        Boolean(request.tools?.length);

      if (useNativeTools) {
        const response = await requestJson(
          config.label,
          `${baseUrl}/chat/completions`,
          {
            method: "POST",
            headers: {
              "content-type": "application/json",
              ...(key ? { authorization: `Bearer ${key}` } : {}),
              ...config.extraHeaders,
            },
            body: JSON.stringify({
              model: request.model,
              messages: request.messages.map(toWireMessage),
              tools: nativeTools(request),
              tool_choice: "auto",
              stream: false,
            }),
            signal: request.signal,
            timeoutMs: 120_000,
          },
        );

        const payload = (await response.json()) as OpenAiToolResponse;
        const toolCall = toolCallAsText(payload);
        if (toolCall) {
          yield toolCall;
          return;
        }

        const content = payload.choices?.[0]?.message?.content;
        if (typeof content === "string" && content.trim()) {
          yield content;
          return;
        }

        return;
      }

      const response = await requestJson(
        config.label,
        `${baseUrl}/chat/completions`,
        {
          method: "POST",
          headers: {
            "content-type": "application/json",
            ...(key ? { authorization: `Bearer ${key}` } : {}),
            ...config.extraHeaders,
          },
          body: JSON.stringify({
            model: request.model,
            messages: request.messages.map(toWireMessage),
            stream: true,
          }),
          signal: request.signal,
          timeoutMs: 120_000,
        },
      );

      yield* parseSseDeltas(response, pickDelta, config.label);
    },
  };
}
